# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.9.0
_src_path: gh:radio-aktywne/template-package-python
accountname: radio-aktywne
description: Signaling utilities for Python 🐍
docs: true
docsurl: https://radio-aktywne.github.io/pyevents
email: it@radioaktywne.pl
importname: pyevents
packagename: pyevents
releases: true
reponame: pyevents
repourl: https://github.com/radio-aktywne/pyevents
